---
language: ruby
before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/stable -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential ruby-dev lxc-dev
  - |
    cat <<EOF | sudo tee /usr/sbin/policy-rc.d
    #!/bin/sh
    exit 101
    EOF
  - sudo chmod 755 /usr/sbin/policy-rc.d
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6"
    gemfile: .gemfile
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.6"
    gemfile: .gemfile
notifications:
  email: false
